services:
  dev-postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=white-labeling-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    
  dev-redis:
    image: redis
    ports:
      - 6379:6379
  
  dev-python:
    build:
      context: python
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - dev-postgres
      - dev-redis

volumes:
  pgdata: